# -*- coding: utf-8 -*-
"""Radiation and Heat Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/buabaj/Radiation-and-Heat/blob/main/Radiation_and_Heat_Analysis.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

clear_data = pd.read_csv('clear-sky-rad.csv')
net_data = pd.read_csv('net-solar-rad.csv')

clear_sky_rad = pd.DataFrame(clear_data)
clear_sky_rad

net_solar_rad = pd.DataFrame(net_data)
net_solar_rad

x = clear_sky_rad.rename(columns={'#   value ':'clear-sky-radiation'})
x

y = net_solar_rad.rename(columns={'#   value ':'net-solar-radiation'})
y

time = pd.DataFrame({
    'time': ['00','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23']
})

time

frames = [time,x,y]
data = pd.concat(frames, axis=1)

data

data.plot(x='time', y=['clear-sky-radiation', 'net-solar-radiation'], figsize=(15, 10), grid=True, kind='line', color=['red','green'], title='Plot of Clear Sky radiation and Net Solar radiation against time for Spintex, 2021-03-20(24hours)')
plt.show()
plt.savefig('RadiationPlot.png')

